pipeline {
    agent any

    environment {
        AWS_REGION    = 'us-east-1'
        PROJECT_DIR   = "$WORKSPACE/flask-todo-app/"
        TERRAFORM_DIR = "$WORKSPACE/flask-todo-app/terraform-setup"
    }

    stages {

        stage("Checking the code") {
            steps {
                git branch: "main", url: "https://github.com/yogithapuppala/Python-project.git"
            }
        }

        stage("Provisioning and Applying Terraform files") {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds'
                ]]) {
                    script {
                        dir(TERRAFORM_DIR) {
                            sh '''
                            echo "Initializing Terraform..."
                            terraform init

                            echo "Applying Terraform configuration..."
                            terraform apply -auto-approve
                            '''
                        }
                    }
                }
            }
        }

        stage("Getting the SNS-Topic-Arn") {
            steps {
                script {
                    dir(TERRAFORM_DIR) {
                        def output = sh(
                            script: 'terraform output -raw sns_topic_arn',
                            returnStdout: true
                        ).trim()
