pipeline {
    agent any

    environment {
        AWS_REGION   = 'us-east-1'
        PROJECT_DIR  = "$WORKSPACE/flask-todo-app/"
        TERRAFORM_DIR = "$WORKSPACE/flask-todo-app/terraform-setup"
    }

    stages {
        stage("Checking the code") {
            steps {
                git branch: "main", url: "https://github.com/yogithapuppala/Python-project.git"
            }
        }

        stage("Provisioning and Applying Terraform files") {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds'
                ]]) {
                    script {
                        dir(TERRAFORM_DIR) {
                            sh '''
                            terraform init
                            echo "Applying the Terraform Files..."
                            terraform apply -auto-approve
                            '''
                        }
                    }
                }
            }
        }

        stage("Getting the SNS-Topic-Arn") {
            steps {
                script {
                    dir(TERRAFORM_DIR) {
                        def output = sh(script: 'terraform output -raw sns_topic_arn', returnStdout: true).trim()
                        env.SNS_TOPIC_ARN = output
                        echo "SNS-Topic-ARN: ${env.SNS_TOPIC_ARN}"
                    }
                }
            }
        }

        stage("Building the Docker Image") {
            steps {
                script {
                    dir(PROJECT_DIR) {
                        sh '''
                        echo "Building Docker image for Flask app..."
                        docker build -t flask-todo-dynamo:v1 .
                        '''
                    }
                }
            }
        }

        stage("Running the Docker Container") {
            steps {
                withCredentials([[
                    $class: 'AmazonWebServicesCredentialsBinding',
                    credentialsId: 'aws-creds'
                ]]) {
                    script {
                        sh '''
                        echo "Running Docker container with AWS environment variables..."
                        docker run -d \
                            -e AWS_REGION=us-east-1 \
                            -e SNS_TOPIC_ARN=${SNS_TOPIC_ARN} \
                            -p 5000:5000 \
                            --name flask-todo-container \
                            flask-todo-dynamo:v1
                        '''
                    }
                }
            }
        }
    }

    post {
        success {
            echo "✅ Pipeline executed successfully!"
        }
        failure {
            echo "❌ Pipeline failed! Please check the logs."
        }
    }
}
